# Minimal packages for the main function

library(TMB)
library(mvtnorm)
library(reshape2)
library(stringr)
library(plyr)
library(dplyr)
library(ggplot2)
library(NbClust)
library(lcmix)
library(vegan)
library(maditr)
library(see)
library(scales)
library(ggrepel)
library(forcats)
library(ppcor)

# Other packages used in the README.md

library(rstan)
library(sf)
library(sp)
library(jsonlite)
library(curl)
library(raster)
library(maps)
library(remotes)
library(viridis)
library(caret)
library(lmtest)
library(devtools)
library(rgeos)
library(rgdal)
library(pforeach)
library(multispatialCCM)
library(rnaturalearth)
library(bayesdfa)
library(arm)
library(maptools)
library(swemaps2)
library(car)
library(plsRglm)
library(dLagM)
library(forecast)
library(vars)
library(rEDM)
library(flexclust)
library(factoextra)
library(cluster)
library(ggpubr)
library(ggimage)
library(emmeans)
library(abind)
library(greenbrown)
