---
title: Short Paper
#author:
#  - name: Alice Anonymous
#    email: alice@example.com
#    affiliation: Some Institute of Technology
#    correspondingauthor: true
#    footnote: 1
#  - name: Bob Security
#    email: bob@example.com
#    affiliation: Another University
#address:
#  - code: Some Institute of Technology
#    address: Department, Street, City, State, Zip
#  - code: Another University
#    address: Department, Street, City, State, Zip
#footnote:
#  - code: 1
#    text: "This is the first author footnote."
#abstract: |
#  This is the abstract.
#  It consists of two paragraphs.
#keywords: 
#  - keyword1
#  - keyword2
#journal: "An awesome journal"
#date: "`r Sys.Date()`"
classoption: preprint, 3p, authoryear
bibliography: MyLibrary.bib
linenumbers: false
numbersections: true
# Use a CSL with `citation_package = "default"`
# csl: https://www.zotero.org/styles/elsevier-harvard
output: 
  rticles::elsevier_article:
    keep_tex: true
    citation_package: natbib
---
# Introduction


Population dynamics are a key to follow the current biodiversity changes. Many species, including common ones, have experienced population declines across the world over the past decades. On the other hand, populations of particular groups of species, for instance generalists, human commensals or hot dwellers have increased. Population dynamics are therefore widely used per se to evaluate the fate of given species of conservation interest, but also aggregated into biodiversity indicators to monitor progress toward conservation targets (e.g. the Living Planet Index). 

Combining population trajectories of multiple species into a Multi Species Index (MSI) enables to summarise the main trajectory of the group of species. MSIs built upon species that share a similar habitat are therefore commonly used as proxies to evaluate the state of a given milieu. For instance, MSIs have been proven useful to raise the alarm on the ongoing decline of farmland birds and to characterise the recovery of some rare wetland birds. Despite the ability of MSI in providing information summarising the main trajectory of a group of species, populations of all these species do not follow the same temporal pattern. More specifically, aggregating the dynamics of several populations into one trajectory can hide trajectories with opposite trends. For instance, a stable MSI could emerge from the aggregation of a similar amount of increasing and decreasing populations. The trajectory of one species can also be driven by factors which do not affect other species with a similar habitat, resulting in an opposite trend for this species. We still lack of approaches that integrate the diversity among population trajectories in species used for a same MSI while keeping the aggregated information given by this MSI.

Until now this issue has been address by analysing separately individual species trajectories and MSI. In MSI, species are grouped a priori (i.e. before knowing their trajectory) according to a shared characteristic. To distinguish groups of species according to their main trajectory, species have to be grouped a posteriori (i.e. once their trajectory is known). This should eventually allows to separate subgroups of species with a similar trajectory within groups of species with a similar habitat, enabling to keeping the habitat information given by aggregated indices like MSI. Dynamic Factor Analysis (DFA) enables to estimate underlying trends of a group of time-series and therefore constitute a means to group species related to a same underlying trend.

In this study, we used the 


# Materiel and methods

## Bird data

Data on abundance of breeding common bird in Sweden have been obtained from @lindstromSwedishBirdSurvey2021. Abundances of 252 bird species have been monitored between 1996 and 2020 on 716 fixed routes consisting in eight 1km-line transects. Counting has been carried out between 20 May and 5 July of each year and has consisted in reporting all bird except young of the year heard or seen, while slowly walking along the transect. 

## Bird time-series

Time-series have been computed for the 168 species with enough data (more than three consecutive year with data, less than four consecutive year without data, data from the first year, a median of occurrence per year > 3, a median of abundance per year > 5 and an overdispersion < 2) between 1998 and 2020 as the number of routes monitored in 1996 and 1997 was relatively low [@lindstromDistributionPopulationChanges2007].

For each species yearly variations from the first year have been obtained using a quasi poisson Generalised Linear Model as follows:

$$
log(\operatorname{Abundance}_{i,j,k}) = \alpha_i + \beta_{1}(\operatorname{Year}_j) + \beta_{2}(\operatorname{Route}_k) + \epsilon
$$
This gave us yearly abundance index for each species and the associated uncertainty.

## Dynamical factor analysis

# Results

# Discussion


# References {-}

